site_name: Visão do Produto e do Projeto - Grupo Orion
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: pt-br
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Mudar para modo escuro
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: mudar para modo claro 
      primary: teal
      accent: lime